-- PSG Production Planning — Supabase schema (matches the Express/SQLite app)
-- Run in Supabase -> SQL Editor -> New query -> Run.

create table if not exists users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password_hash text not null,
  role text not null default 'team',
  created_at timestamptz default now()
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  order_number text unique not null,
  parent_order text,
  height_mm real default 0,
  width_mm real default 0,
  order_date date,
  delivery_date date,
  order_type text default 'Architectural',
  client_name text default '',
  ct int default 0,
  gr int default 0,
  pe int default 0,
  bv int default 0,
  hl int default 0,
  pr int default 0,
  tg int default 0,
  bg int default 0,
  lg int default 0,
  fr int default 0,
  dg int default 0,
  qc int default 0,
  order_qty int default 0,
  status text default 'Active',
  notes text default '',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists wc_progress (
  id bigint generated by default as identity primary key,
  order_id bigint not null references orders(id) on delete cascade,
  work_center text not null,
  received_qty int default 0,
  done_qty int default 0,
  started_at timestamptz,
  completed_at timestamptz,
  updated_by text,
  updated_at timestamptz default now(),
  unique(order_id, work_center)
);

create table if not exists ncr (
  id bigint generated by default as identity primary key,
  order_id bigint not null references orders(id) on delete cascade,
  work_center text not null,
  qty_rejected int not null,
  type text not null,
  reason text,
  created_by text,
  resolved int default 0,
  created_at timestamptz default now()
);

create table if not exists holidays (
  id bigint generated by default as identity primary key,
  holiday_date date unique not null,
  name text not null
);

create table if not exists capacity (
  id bigint generated by default as identity primary key,
  work_center text unique not null,
  capacity_sqft real not null
);

alter table users enable row level security;
drop policy if exists "demo" on users;
create policy "demo" on users for all using (true) with check (true);
alter table orders enable row level security;
drop policy if exists "demo" on orders;
create policy "demo" on orders for all using (true) with check (true);
alter table wc_progress enable row level security;
drop policy if exists "demo" on wc_progress;
create policy "demo" on wc_progress for all using (true) with check (true);
alter table ncr enable row level security;
drop policy if exists "demo" on ncr;
create policy "demo" on ncr for all using (true) with check (true);
alter table holidays enable row level security;
drop policy if exists "demo" on holidays;
create policy "demo" on holidays for all using (true) with check (true);
alter table capacity enable row level security;
drop policy if exists "demo" on capacity;
create policy "demo" on capacity for all using (true) with check (true);